//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDo.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Todo
    {
        public int TodoId { get; set; }
        public string Description { get; set; }
        public bool Completed { get; set; }
    }
}
